plugins { id 'com.android.application' }

android {
    namespace 'kr.dutchpay'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId 'kr.dutchpay'
        minSdk 26
        targetSdk 35
        versionCode 10
        versionName '0.8.2'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    if (project.hasProperty('fullPaddle')) sourceSets.androidTest.java.srcDir 'src/paddleTest/java'
}
dependencies {
    implementation 'com.google.mlkit:text-recognition-korean:16.0.1'
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.21.1'
    implementation project(':paddle-sdk')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
